service: appTracker
plugins:
  - serverless-offline

custom:
  defaultNodePath: '../../layers/nodejs/node_modules'
  nodePathLib: '../layers/nodejs/node_modules'

  localhost:
    environment:
      NODE_PATH: ${self:custom.nodePathLib}:${self:custom.defaultNodePath}:../..:.
      handlerPath: ../../

  stages:
    secrets:
      production: 'production' # --stage=production
      other: 'dev' # anything else
    current: ${self:custom.stages.secrets.${opt:stage}, self:custom.stages.secrets.other}

  apisecret: ${ssm:/aws/reference/secretsmanager/${self:custom.stages.current}-tracker}

provider:
  name: aws
  runtime: nodejs18.x
  nodeOptions:
    # Required to enable fetch on node 18.
    - --enable-undici
  versionFunctions: true
  stage: ${opt:stage}
  region: us-east-1
  deploymentBucket:
    name: ${self:custom.apisecret.BUCKET}

  environment:
    NODE_PATH: ${self:custom.${opt:stage}.environment.NODE_PATH, ''}
    STAGE: ${self:provider.stage}
    CURRENT_ENV: ${self:provider.stage}
    DATABASE_HOST: ${self:custom.apisecret.DATABASE_HOST}
    DATABASE_USER: ${self:custom.apisecret.DATABASE_USER}
    DATABASE_NAME: ${self:custom.apisecret.DATABASE_NAME}
    DATABASE_PASSWORD: ${self:custom.apisecret.DATABASE_PASSWORD}
    DATABASE_PORT: ${self:custom.apisecret.DATABASE_PORT}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
      Resource: '*'

package:
  include:
    - ../../libs/**
    - ../../vendor/**
    - ../../entityQueries/**
    - ../../utils/**
  exclude:
    - node_modules/**

functions:
  proxy:
    tracing: true
    timeout: 300
    memorySize: 2048
    handler: handler.app
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            allowCredentials: false
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    layers:
      - ${self:custom.apisecret.LAYERS, ''}
