service: layers

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

layers:
  nodejs:
    name: appTracker-${opt:stage, 'dev'}-layers
    description: 'slsv2 dependencies'
    path: ../layers
    compatibleRuntimes:
      - nodejs20.x
      - nodejs18.x
      - nodejs16.x

resources:
  Outputs:
    NodejsLayerExport:
      Value:
        Ref: NodejsLambdaLayer
      Export:
        Name: appTracker-${opt:stage, 'dev'}-NodejsLambdaLayer
